### ISSUE TITLE
Quick view pagination error across page boundary when dataProvider=0

### ISSUE THREAD

**Issue by danielwu68** [jamesdruhan/vue-jd-table#11]
The `Quick View` pagination uses `currentTableData` as data source for rendering but uses `processedDataSize` for pagination.  The `processedDataSize` can be greater than `currentTableData.length` which causes pagination error.

Steps to reproduce:

1. dataProvider=0 or unset
2. set the page row size to small so the pagination can happen
3. double click on any row to open Quick View
4. attempt to navigate beyond the page will cause the error below

A related error

1. dataProvider=0 or unset
2. set the page row size to small so the pagination can happen
3. navigate to any page other then the first page
4. double click to open Quick View will cause the error below also

```text
[Vue warn]: Error in render: "TypeError: t.currentTableData[t.row.selectedIndex] is undefined"

found in

---> <JDTable>
       <AccountList>
         <AccountVue> at src/views/account.vue
           <App> at src/App.vue
             <Root>
```

**Comment by jamesdruhan** [comment]
This will be fixed in 1.1.3. Thanks!
