### ISSUE TITLE
your Table is awesome

### ISSUE THREAD

**Issue by ahmedmohamedmariy** [jamesdruhan/vue-jd-table#16]
Hi my friend your jd-table in awesome but icant use with laravel api and i watch Display data but not work . if you had full example for get data from api please send to me.
Thank you again

**Comment by jamesdruhan** [comment]
@ahmedmohamedmariy JD-Table doesn't directly connect to any API (this is pretty normal for JS tables). So long as you format the data received by your API to the format needed by JD-Table it will display your data accordingly. As such, I don't really have a external API example.

Here is the existing examples I have [🔗](https://github.com/jamesdruhan/vue-jd-table/tree/master/docs/demo) . Just replace the created method with your own API call promise and set the data for JD-Table.
