### ISSUE TITLE
scroll to a specific row 

### ISSUE THREAD

**Issue by marcdakar** [jamesdruhan/vue-jd-table#18]
hi there,
can i scroll to a specific row,
or to a specific Ypos of the table

with over 10.000 rows i like to come back to same table position -> after row detail view in other page

thank you very much
many greetings marc

**Comment by jamesdruhan** [comment]
Hi Marc,

Unfortunately at this time a Y position scroll is not available. However this is a pretty good idea. I'll keep in it mind for future updates.
