### ISSUE TITLE
Don't work the option contextMenuRight

### ISSUE THREAD

**Issue by juanitourquiza** [jamesdruhan/vue-jd-table#19]
I have this configuration:
```
this.tableOptions =
            {
                title: null,
                columns: this.columns,
                quickView: true,
                contextMenu: true,
                contextMenuRight: true,
                contextMenuQuickView: true,
                contextMenuEdit: true,
                contextMenuDelete: true,
                addNew: true
            };
```
But I don't see the options?
What is the problem?

![image](https://user-images.githubusercontent.com/332299/99138638-0921d600-2600-11eb-8422-cd45f448532c.png)

**Comment by jamesdruhan** [comment]
@juanitourquiza can you be a bit more specific? Which options are you expecting to see?

**Comment by juanitourquiza** [comment]
@jamesdruhan Hi, I thought this option can to show a button with the options Edit, Insert, Add or it's possible I add an URL or path in the Id?

**Comment by jamesdruhan** [comment]
Hi @juanitourquiza, the context menu is shown when left or right clicking a row of data. I would recommend enabling only one (left or right):

`this.tableOptions =
{
      title: null,
      columns: this.columns,
      contextMenuRight: true,
      contextMenuQuickView: true,
      contextMenuEdit: true,
      contextMenuDelete: true,
      addNew: true
};`

Enable left click: **contextMenu: true**
Enable right click: **contextMenuRight: true**

**Comment by juanitourquiza** [comment]
Maybe, it's possible a path in the id to the other page for example?

**Comment by jamesdruhan** [comment]
Sorry, I'm not sure I understand your suggestion. I'm going to close this topic for now as there is no current issue. If you need some sort of custom functionality, I highly encourage you to fork and try it out!
