### ISSUE TITLE
Array Data not supported

### ISSUE THREAD

**Issue by jamesdruhan** [jamesdruhan/vue-jd-table#2]
JD-Table does not support data with an array of strings/numbers. If passed to JD-Table they are rendered as a javascript object.

**Comment by keepercito** [comment]
i tried to use this npm package to display some data using laravel 5.8. I followed all documentation instructions but when charge data, i have a transition problem like this
![photo_2019-08-19_18-01-19](https://user-images.githubusercontent.com/16314700/63307479-c3b31380-c2ab-11e9-88f7-8167fe28d017.jpg)
Helping by some class mates we change the transition to tramstion-group on line 335, but we faced with the following problem
![photo_2019-08-19_18-01-24](https://user-images.githubusercontent.com/16314700/63307560-0d9bf980-c2ac-11e9-9b72-e8b049d29227.jpg)

will known what are we doing wrong to trying to use this package with laravel 5.8

**Comment by jamesdruhan** [comment]
@keepercito I understand the error you are getting and unfortunately transition-group will not work. This is due to the fact that there should only be one JD-Table Popup enabled at a given time. I've troubleshooted this in the past and was able to manipulate the statuses so that they didn't clash and I haven't received this error in some time.

Do you have some sample code I could take a look at? For example, how you are initializing and triggering data to JD-Table. Also, ensure you are setting the tableLoader prop to false after triggering the data.

`// Enable the table loader.`
`this.tableLoader = true;`

`this.eventFromApp =`
`{`
	`name           : 'sendData',`
	`payload        : JSON.parse( data ),`
`};`

`this.triggerEvent();`

`// Disable the table loader. *** MAKE SURE THIS IS DONE ***`
`this.tableLoader = false;`

**Comment by keepercito** [comment]
thanks for responding... i have to told you that i don't have the error anymore, i don't know why (seriously xD) my code was based on the default demo do you on the plugin page. If i face the error on the future or something else, i will report it
