### ISSUE TITLE
Dynamic columns

### ISSUE THREAD

**Issue by mokchend** [jamesdruhan/vue-jd-table#21]
Hello,
Is there a way to set the table columns dynamically ?
**Use case**: when query an external API, theses fields will become the table columns to be display.
Hardcoding the columns in my vue instance works, but when i tried to modify my options, nothing happens
this.tableOptions.columns = [ ... {dynamic Col1} ... ]

**Comment by jamesdruhan** [comment]
The columns need to be predefined when JDTable is initialized. There is a lot that goes into ensuring individual columns are displayed correctly and are responsive. So new columns added to that array may not be reactive. Existing columns should be. Perhaps you could predefined all potential columns but hide them and only show them after the query data is returned.
