### ISSUE TITLE
Not working with nuxt!

### ISSUE THREAD

**Issue by rohitnishad613** [jamesdruhan/vue-jd-table#22]
I just try to install it via npm it installs but not works
Nuxt gives a error of `component not defined vue`
I get deep into it, and I think

THE IS THIS COMPONENT IS NOT ESLINT FRIENDLY

btw, anyone how to use this vue-jd-table in nuxt?

**Comment by jamesdruhan** [comment]
The vue-jd-table is a VueJS component add-on. It requires VueJS 2.x. Sorry, I actually don’t think I specified that officially in the docs.

Also, you are correct, this package does not use ESLint.

**Comment by rohitnishad613** [comment]
how to configure it with nuxt?

**Comment by rohitnishad613** [comment]
Why you closed this issue?
I have issues with nuxtJS.

Can you please tell me how to configure it with nuxt.js?

**Comment by jamesdruhan** [comment]
Hi Rohit, sorry but I am not familiar with Nuxt.JS so I have to assume it might not be compatible as I've never done any testing. This is just a regular VueJS component with nothing fancy. You might need to look for a table solution that is specifically for Nuxt.
