### ISSUE TITLE
customize via slot

### ISSUE THREAD

**Issue by cannap** [jamesdruhan/vue-jd-table#6]
Hi, the component looks very good but does it support slots for tr/ td what ever?
i checked the docs but cant find any about this.

atm i use vue-good-table but i think about to switch

in vue good-tabele i can do 

 ```vue
<template v-slot:table-row="{ column, row }">
      <span v-if="column.field == 'showMarket'">
        <RouteLink
          :label="$t('tables.markets.button')"
          :route="{ name: 'market-id', params: { id: row.id } }"
        />
      </span>
    </template>
```
and does it support ssr?
thanks

**Comment by jamesdruhan** [comment]
Unfortunately JD-Table does not currently support slotted content right now. I do indeed plan on adding this functionality, specifically to allow users to create/add custom feature button functionality (like your example). Finally, JD-Table has not be developed with SSR in mind.

**Comment by cannap** [comment]
thank you
